Table pc {
  id int [increment, primary key]
  marqueId int
  osId int
  disqueGB int
  ramGB int
  dateAchat date
  user varchar
}

Table marque {
  id int [increment, primary key]
  nom varchar
}

Table os {
  id int [increment, primary key]
  nom varchar
}

Table logiciel_instal {
  id int [increment, primary key]
  pcId int
  logicielId int
  techInstal int
}

Table logiciel {
  id int [increment, primary key]
  nom varchar
  licence varchar
  version varchar
}

Table technicien {
  id int [increment, primary key]
  nom varchar
  dateInterv date
  pcInterv int
}

Table maj {
  id int [increment, primary key]
  pcMaj int
  techMaj int
  dateMaj date
}

ref: logiciel_instal.pcId > pc.id
ref: logiciel_instal.logicielId > logiciel.id
ref: pc.marqueId > marque.id
ref: pc.osId > os.id
ref: maj.pcMaj > pc.id
ref: maj.techMaj > technicien.id
ref: technicien.pcInterv > pc.id
ref: logiciel_instal.techInstal > technicien.id
