#/bin/bash

sed s/settings?.headercolor/settings.headercolor/ /usr/local/lib/node_modules/@softwaretechnik/dbml-renderer/lib/renderer.js > correctionjs
cp correctionjs /usr/local/lib/node_modules/@softwaretechnik/dbml-renderer/lib/renderer.js
rm correctionjs

sed 's/GENERATED BY DEFAULT AS IDENTITY/AUTO_INCREMENT/g' /srv/sae51db.sql > sqlcorrige
cp sqlcorrige /srv/sae51db.sql